sudo: required
language: python

env:
  global:
  - DOCKER_IMAGE=getpagespeed/rpmbuilder
  - OS_ARCH=x86_64
  matrix:
  - OS_TYPE=centos OS_DIST=epel OS_VERSION=7

services:
- docker

install: true

before_install:
- gem install package_cloud

script:
- docker run -v ${PWD}:/sources -v ${PWD}:/output:Z ${DOCKER_IMAGE}:${OS_TYPE}-${OS_VERSION}
- rm -rf *.src.rpm
- stat *.rpm

after_success:
- package_cloud push getpagespeed/extras/el/7 *.rpm
