env:
  global:
    - DOCKER_IMAGE=getpagespeed/rpmbuilder
    - OS_ARCH=x86_64
  matrix:
    - OS_TYPE=centos OS_DIST=epel OS_VERSION=6
    - OS_TYPE=centos OS_DIST=epel OS_VERSION=7
    - OS_TYPE=centos OS_DIST=epel OS_VERSION=8

services:
  - docker

before_install:
  - test $TRAVIS_BRANCH = "master" && gem install package_cloud

script:
  - docker run -v ${PWD}:/sources -v ${PWD}:/output:Z ${DOCKER_IMAGE}:${OS_TYPE}-${OS_VERSION}
  - rm -rf *.src.rpm

after_success:
  - test $TRAVIS_BRANCH = "master" && package_cloud push getpagespeed/extras/el/6 *.el6*.rpm
  - test $TRAVIS_BRANCH = "master" && package_cloud push getpagespeed/extras/el/7 *.el7*.rpm
  - test $TRAVIS_BRANCH = "master" && package_cloud push getpagespeed/extras/el/8 *.el8*.rpm
