version: 2
jobs:
  build:
    machine: true
    steps:
      - run:
          name: "Delete stupid keys that was added by CircleCI by default"
          command: ssh-add -D
      - add_ssh_keys:
          fingerprints:
            - "8c:a4:dd:2c:47:4c:63:aa:90:0b:e0:d6:15:be:87:82"
      - run:
          name: "Clean old job's artifacts and log files."
          command: ssh $GPS_BUILD_USER@$GPS_BUILD_SERVER "cd ~/xmrig-rpm; git clean -fX"
          context: getpagespeed-builder
      - run:
          name: "Just trigger out githook build, kind of."
          command: ssh $GPS_BUILD_USER@$GPS_BUILD_SERVER "launch2log.sh ~/xmrig-rpm/rebuild.sh ~/xmrig-rpm/rebuild.log"
          context: getpagespeed-builder 
